services:
  - type: web
    name: student-directory-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn student_directory.wsgi:application"
    envVars:
      - key: RENDER
        value: "1"
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: student-directory-db
          property: connectionString
